#!/bin/sh

if [ $# -eq 0 ]; then
    echo "Usage:"
    echo -e "\t$0 <file_to_convert>"
    exit 1
fi

mv "$1" "$1.old"

sed 's/pthread_mutex_/pi_mutex_/g' "$1.old" | \
sed 's/pthread_cond_/pi_cond_/g' | \
sed 's/\(pi_cond_wait[\s]*([^,]*\)\([^\)]*\)/\1/g' | \
sed 's/\(pi_cond_timedwait[\s]*([^,]*\)\(,[^,]*\)\([^\)]*\)/\1\3/g' > "$1"
